# -*- coding: utf-8 -*-
"""Scrapping Web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Ypa21f_GcTBexsAMuu_33n3L3Y0NbRt
"""

import requests
from bs4 import BeautifulSoup
import json
import csv

base_url = "http://books.toscrape.com/catalogue/page-{}.html"

data = []

for page in range(1, 4):
    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        rating = book.p["class"][1]

        data.append({
            "title": title,
            "price": price,
            "rating": rating
        })

print("Jumlah data:", len(data))

with open("books.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=4, ensure_ascii=False)

with open("books.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["title", "price", "rating"])
    writer.writeheader()
    writer.writerows(data)

print("✅ Data berhasil disimpan!")

from google.colab import files

files.download("books.json")
files.download("books.csv")